### ISSUE TITLE
delay between requests

### ISSUE THREAD

**Issue by spoNge369** [RedTeamPentesting/monsoon#15]
Hii, it would be nice to add a --delay option between the sent requests :)

**Comment by rtpt-alexanderneumann** [comment]
What's your use case? What are you trying to do?

Did you discover `--requests-per-second` yet?

**Comment by spoNge369** [comment]
the flag works fine, but for the case where the delay has to be random, something like --requests-per-second 0.5-1?, it would be like from 1 request per 2 seconds to 1 request per second

**Comment by rtpt-alexanderneumann** [comment]
What are you trying to do? Why do you need a random delay?

I'm trying to find out whether it's a good idea to implement such behavior in monsoon. In order to convince me, it would need to be a feature that many people can use so it warrants the implementation and maintenance time we have to invest.

For some applications/attacks, it's much better to implement your own program/script that's specifically tailored to your use case.

**Comment by rtpt-erikgeiser** [comment]
I'm closing this issue for now. If you want to explain your use-case for random delays, feel free to re-open it.
